project:
  type: website
  output-dir: docs

website:
  title: "Auswertung der Kurzskala intrinsische Motivation (KIM)"
  favicon: logo.png
  page-footer: "CC BY-SA 4.0" 
  navbar:
    left:
      - href: index.qmd
        text: Hintergrund
      - blersch_KIM_analyse_20260102_website.qmd
      - theoriePraxis.qmd
      - about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/GeowazM

format:
  html:
    theme:
      light: lumen
      dark: darkly
    toc: true

editor: visual

